//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class discount
    {
        public int discount_id { get; set; }
        public Nullable<int> discount_size { get; set; }
        public Nullable<int> goods_ID { get; set; }
        public Nullable<System.DateTime> discount_date { get; set; }
    
        public virtual goods goods { get; set; }
    }
}
